language: go

go:
  - 1.6
  - 1.8.1
  - tip

install:
  - go get -u google.golang.org/appengine/...
  - mkdir /tmp/sdk
  - curl -o /tmp/sdk.zip "https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.48.zip"
  - unzip -q /tmp/sdk.zip -d /tmp/sdk
  - export PATH="$PATH:/tmp/sdk/go_appengine"
  - export APPENGINE_DEV_APPSERVER=/tmp/sdk/go_appengine/dev_appserver.py

script:
  - goapp version
  - go version
  - goapp install ./...
  - goapp test -v ./...
